version: 2
updates:
- package-ecosystem: maven
  directory: /
  schedule:
    interval: weekly
  reviewers:
      - "jetersen"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  reviewers:
      - "jetersen"
